# Practical 21 - Practice Questions II

Attempt these practice questions to revise on functions, dictionaries and CSV file handling. After writing your code as required, run the cells containing the test cases and check your output against the expected output.

### Question 1

Implement a function `get_mean_median()` which takes in a list of integers. It returns a tuple containing the mean value followed by the median value of the list. 
* When the list has an odd number of integers, its median value is the middle value of the sorted list.
* When the list has an even number of integers, its median value is average of the middle 2 values.

You get an extra bonus mark if your function does not modify the input parameter list.

In [58]:
# WRITE YOUR CODE HERE
import statistics

def get_mean_median(n):

    n.sort()
    half = len(s)//2

    if len(n) %2 ==0:
        return float(statistics.mean(n)),(n[half-1] + n[-half])/2
        
    if len(n) %2 != 0:
        return float(statistics.mean(n)),n[half] 


<u>*Test Case 1*</u>

Input: `[1, 3]`<br>
Expected output: `(2.0, 2.0)`<br>
Note that because there is an even number of integers, the median is the average of the middle 2 sorted values, 1 and 3.

In [60]:
s = [1, 3]
get_mean_median(s)

(2.0, 2.0)

<u>*Test Case 2*</u>

Input: `[999, 1, 2]`<br>
Expected output: `(334.0, 2)`<br>
Note that because there is an odd number of integers, the median is just the middle sorted value, 2.

In [59]:
s = [999, 1, 2]
get_mean_median(s)

(334.0, 2)

<u>*Test Case 3*</u>

Input: `[8, 6, 4, 5, 18, 7]`<br>
Expected output: `(8.0, 6.5)`

In [61]:
s = [8, 6, 4, 5, 18, 7]
get_mean_median(s)

(8.0, 6.5)

### Question 2

Implement a function `count_divisibles(s)` which takes in a list of integers; it counts the number of integers in the list that can be divided by 2, 3 and 5 respectively. 

The result is returned in a dictionary. For example, `{2: 5, 3: 2, 5: 0}` indicates that 5 numbers can be divided by 2, 2 numbers can be divided by 3, and no numbers can be divided by 5. 

In [71]:
# WRITE YOUR CODE HERE
def count_divisibles(s):
    diction  = {2:0,3:0,5:0}
    for i in range(len(s)):
        for h in diction:
            if s[i] % h == 0:
                diction[h] = diction[h] +1
    return diction


<u>*Test Case 1*</u>

Input: `[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]`<br>
Expected output: `{2: 5, 3: 3, 5: 2}`<br>
This is because in the list there are 5 integers that can be divided by 2 (`2`, `4`, `6`, `8`, `10`), 3 integers that can be divided by 3 (`3`, `6`, `9`) and 2 integers that can be divided by 5 (`5`, `10`).

In [72]:
count_divisibles([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

{2: 5, 3: 3, 5: 2}

<u>*Test Case 2*</u>

Input: `[11, 13]`<br>
Expected output: `{2: 0, 3: 0, 5: 0}`<br>
This is because neither `11` nor `13` are divisible by 2, 3 or 5.

In [73]:
count_divisibles([11, 13])

{2: 0, 3: 0, 5: 0}

### Question 3: Processing CSV File

The `"graduates.csv"` file in the `"data"` folder contains the number of university degree graduates by year, sex and type of course.

```
year,sex,type_of_course,no_of_graduates
1993,Males,Education,na
1993,Males,Applied Arts,na
1993,Males,Humanities & Social Sciences,481
1993,Males,Mass Communication,na
1993,Males,Accountancy,295
1993,Males,Business & Administration,282
```

(reference: [https://data.gov.sg/dataset/graduates-from-university-first-degree-courses-by-type-of-course](https://data.gov.sg/dataset/graduates-from-university-first-degree-courses-by-type-of-course))

----
**A)** Write a function `load_graduate_data(file)`, where `file` is the path to the CSV file, to read the file and return a list of records.

* Each record (data point) in the list is a tuple, e.g. `(1993,'Males','Humanities & Social Sciences',481)`.
* The `year` and `no_of_graduates` are converted to integer values.
* Exclude header row in the returned list.
* Exclude records whose `no_of_graduates` column are non-numeric values, e.g. `na`.  

Note: Use `str.isnumeric()` function to check if a string is of numeric values.

In [97]:
# WRITE YOUR CODE HERE
import os
import csv

def load_graduate_data(file):
    with open(file,'r') as f:

        reader = csv.reader(f)
        header = next(reader)
        data = []

        for row in reader:
            row[0] = int(row[0])

            if row[3].isnumeric() == False:
                    continue
            else:
                row[3] = int(row[3])

            data.append(tuple(row))

        return data

<u>*Test Case*</u>

In [98]:
file_name = 'data/graduates.csv'
table = load_graduate_data(file_name)

print("Record count: ", len(table))
print(table[:2])
print(table[-2:])

Record count:  600
[(1993, 'Males', 'Humanities & Social Sciences', 481), (1993, 'Males', 'Accountancy', 295)]
[(2014, 'Females', 'Engineering Sciences', 1251), (2014, 'Females', 'Services', 219)]


Expected output:

```
Record count:  600
[(1993, 'Males', 'Humanities & Social Sciences', 481), (1993, 'Males', 'Accountancy', 295)]
[(2014, 'Females', 'Engineering Sciences', 1251), (2014, 'Females', 'Services', 219)]
```

----
**B)** Write a function `graduates_by_course(table, start_year, end_year)` to find the total number of graduates from `table` between `start_year` and `end_year` (both inclusive) for all courses.
* The `table` data is the same data returned from `load_graduate_data()` function.
* It returns a dictionary whose key is the course type, and value is the total graduate number between the years. 

In [117]:
# WRITE YOUR CODE HERE
def graduates_by_course(table,start_year,end_year):
    diction = {}
    for i in table:
        if i[0] < start_year or i[0] > end_year:
            continue
        #print(i[0],'accepted')
        if diction.get(i[2]) == None:
            diction[i[2]] = i[3]
            #print('added ',i[3], 'to new', i[2],'dict')
        else:
            diction[i[2]] = diction[i[2]] + i[3]
            #print('added', i[3], 'to', i[2])
    return diction
            

<u>*Test Case*</u>

In [118]:
# The following 3 lines are needed if you have not completed 1(A).
import pickle
with open('raw/graduates.pickle', 'rb') as handle:
    table = pickle.load(handle)

result = graduates_by_course(table, 2000, 2004)
print(len(result))
print(result)

14
{'Education': 1359, 'Humanities & Social Sciences': 9264, 'Mass Communication': 609, 'Accountancy': 3620, 'Business & Administration': 5502, 'Law': 744, 'Natural, Physical & Mathematical Sciences': 5423, 'Medicine': 870, 'Dentistry': 165, 'Health Sciences': 325, 'Information Technology': 2821, 'Architecture & Building': 1706, 'Engineering Sciences': 17931, 'Applied Arts': 46}


Expected output:

```
14
{'Education': 1359, 'Humanities & Social Sciences': 9264, 'Mass Communication': 609, 'Accountancy': 3620, 'Business & Administration': 5502, 'Law': 744, 'Natural, Physical & Mathematical Sciences': 5423, 'Medicine': 870, 'Dentistry': 165, 'Health Sciences': 325, 'Information Technology': 2821, 'Architecture & Building': 1706, 'Engineering Sciences': 17931, 'Applied Arts': 46}
```

----
**C)** Write a function `save_graduates_by_course(data, file)` to save data to a CSV file, where `data` is a dictionary returned from function `graduates_by_course()`, and `file` is the output file path.
* Each row in the CSV file is in `course, count` format. There is no header row.

In [144]:
# WRITE YOUR CODE HERE
def save_graduates_by_course(data,file):
    with open(file, 'w') as f:
        writer = csv.DictWriter(f, fieldnames= ["Course", "Count"])
        writer.writerows(data)
        #i do no understand why this does not work

<u>*Test Case*</u>

In [145]:
# The following 3 lines are needed if you have not completed 1(A).
import pickle
with open('raw/graduates.pickle', 'rb') as handle:
    table = pickle.load(handle)

result = graduates_by_course(table, 2000, 2004)
print(result)
save_graduates_by_course(result, 'data/result.csv')

with open('data/result.csv') as f:
    data = [r.strip() for r in f.readlines()]
    data.sort()
    print(len(data))
    print(data)

{'Education': 1359, 'Humanities & Social Sciences': 9264, 'Mass Communication': 609, 'Accountancy': 3620, 'Business & Administration': 5502, 'Law': 744, 'Natural, Physical & Mathematical Sciences': 5423, 'Medicine': 870, 'Dentistry': 165, 'Health Sciences': 325, 'Information Technology': 2821, 'Architecture & Building': 1706, 'Engineering Sciences': 17931, 'Applied Arts': 46}


AttributeError: 'str' object has no attribute 'keys'

Expected output:

```
14
['"Natural, Physical & Mathematical Sciences",5423', 'Accountancy,3620', 'Applied Arts,46', 'Architecture & Building,1706', 'Business & Administration,5502', 'Dentistry,165', 'Education,1359', 'Engineering Sciences,17931', 'Health Sciences,325', 'Humanities & Social Sciences,9264', 'Information Technology,2821', 'Law,744', 'Mass Communication,609', 'Medicine,870']
```